name: PR Render

on:
  # allows for manual triggering from github
  workflow_dispatch:
  pull_request:
    paths:
      - 'blender/**'


jobs:
  Scene-Render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.1.0
        with:
          path: scripts/requirements.txt

      - name: Set the new relative paths
        run: make set_paths

      - name: Create Raw (simple) Render from Scene
        run: |
          echo "Creating inital buffer frames"
          make scene_render

      # - name: Create Raw (cool) Render from Scene
      #   run: |
      #     echo "Creating inital buffer frames"
      #     make cool_scene_render

      - name: Upload Buffer Images as Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: buffer
          path: imgs/buffer/
